### ISSUE TITLE
Server IP gets banned when trying to read feeds.

### ISSUE THREAD

**Issue by kjellberg** [awjudd/l4-feed-reader#19]
Somehow this script makes remote servers ban my server IP with modsecurity.

### What I'm trying to do:
```php
$feed = FeedReader::read($url);
```
### First request
> cURL error 22: The requested URL returned error: 400 Bad Request

### Following requests
> cURL error 28: Connection timed out after 10001 milliseconds

And then I can't access the ip at all after trying to parse a feed on that server. I don't know if this problem is for all servers using modsecurity or if it's related to SiteGrounds configurations.

**Comment by awjudd** [comment]
@kjellberg How many requests are you making to the site?  What it sounds like you need is a proxy of some sort.  However, that is outside of the scope of this project.

**Comment by kjellberg** [comment]
Thank you for a fast answer @awjudd. Only one request and then I get banned so I don't know if proxies would help. I tried this from multiple servers and the problem occurs everywhere (CURL 400 Bad Request errors). 

I tried to parse a feed from my local computer and then I could't reach the page from my browser (it worked before my FeedReader request), contacted the hosting support and they told me that IPs were blocked by mod_security.

Maybe this has something to do with the headers that is sent when downloading a feed? Is this SimplePie related?

**Comment by awjudd** [comment]
@kjellberg I believe so - try to make a sample application locally which just uses the core SimplePie library (without Laravel) and make the request.  If you don't get the IP ban on that connection, then it's something with this package and I will take more information about it.  However, if it still happens when using straight SimplePie, then it has something to do with the request that they send so maybe they will be able to provide more in-depth support with regards to this issue.
